name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: echo 0 | ./configure 
    - name: make
      run: cp efistub.c main.c ; make
