name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: archlinux-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: pacman -S gnu-efi-libs;echo 1 | ./configure
    - name: make
      run: make
